In [2]:
# import pandas and numpy

import pandas as pd
import numpy as np

In [3]:
# Create dataframe out of csv file: breach_report.csv

df = pd.read_csv('breach_report.csv')

#inspect dataframe using .head()
df.head()

,Name of Covered Entity,State,Covered Entity Type,Individuals Affected,Breach Submission Date,Type of Breach,Location of Breached Information,Business Associate Present,Web Description
0,Humana Inc,KY,Health Plan,863.0,06/03/2019,Unauthorized Access/Disclosure,Network Server,No,NaN
1,Delta Dental of Illinois,IL,Business Associate,4216.0,04/17/2019,Hacking/IT Incident,Email,Yes,Breach #19-340335 will be consolidated into Br...
2,Providence Health Plan,OR,Health Plan,651.0,03/19/2019,Theft,Laptop,Yes,An unencrypted laptop computer containing the ...
3,ZOLL Services LLC,PA,Healthcare Provider,277319.0,03/18/2019,Hacking/IT Incident,Network Server,Yes,"Sonian, a subcontractor of the covered entity’..."
4,Pasquotank-Camden Emergency Medical Service,NC,Healthcare Provider,20420.0,02/28/2019,Hacking/IT Incident,Network Server,No,"On December 14, 2018, Pasquotank-Camden Emerge..."

# Drop columns that are not needed

In [4]:
# Drop columns that are not needed: Ex. _____ using .drop()
df.drop(columns=['Web Description'], inplace=True)

#inspect dataframe using .head()
df.head()

,Name of Covered Entity,State,Covered Entity Type,Individuals Affected,Breach Submission Date,Type of Breach,Location of Breached Information,Business Associate Present
0,Humana Inc,KY,Health Plan,863.0,06/03/2019,Unauthorized Access/Disclosure,Network Server,No
1,Delta Dental of Illinois,IL,Business Associate,4216.0,04/17/2019,Hacking/IT Incident,Email,Yes
2,Providence Health Plan,OR,Health Plan,651.0,03/19/2019,Theft,Laptop,Yes
3,ZOLL Services LLC,PA,Healthcare Provider,277319.0,03/18/2019,Hacking/IT Incident,Network Server,Yes
4,Pasquotank-Camden Emergency Medical Service,NC,Healthcare Provider,20420.0,02/28/2019,Hacking/IT Incident,Network Server,No

# Transform data types where applicable

In [8]:
# Determine data types using .dtypes
df.dtypes

Name of Covered Entity               object
State                                object
Covered Entity Type                  object
Individuals Affected                float64
Breach Submission Date               object
Type of Breach                       object
Location of Breached Information     object
Business Associate Present           object
dtype: object

In [9]:
# Transform objects to numerical values where applicable (Ex. Column = Breach Submission Date)
# Transform object 'Breach Submission Date' to type date time using .to_datetime()
df['Breach Submission Date'] = pd.to_datetime(df['Breach Submission Date'])

# Confirm 'Breach Submission Date' column is in type date time
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2315 entries, 0 to 2314
Data columns (total 8 columns):
Name of Covered Entity              2315 non-null object
State                               2312 non-null object
Covered Entity Type                 2313 non-null object
Individuals Affected                2314 non-null float64
Breach Submission Date              2315 non-null datetime64[ns]
Type of Breach                      2314 non-null object
Location of Breached Information    2315 non-null object
Business Associate Present          2315 non-null object
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 144.8+ KB
None

In [10]:
# Using .shape() determine how large the dataset is
df.shape

(2315, 8)

# Drop nulls

In [11]:
# Check all columns for null values using .isnull() and .sum() 
null = df.isnull().sum()
null

Name of Covered Entity              0
State                               3
Covered Entity Type                 2
Individuals Affected                1
Breach Submission Date              0
Type of Breach                      1
Location of Breached Information    0
Business Associate Present          0
dtype: int64

In [12]:
# Drop nulls using .dropna() on the dataframe 
# (or fill in ) --
# Note: State column has 3 null values, Covered Entiity Type column has 2 null values, Individuals Affected has 1 null value,
# Type of Breach has 1 null value, Web Description has 225 null values

dropped = df.dropna()

#Inspect dataframe size using .shape to ensure all 232 null rows were dropped
dropped.shape

#use dropped dataframe moving forward

(2308, 8)

# Duplicate values

# Name of Entity Covered

In [13]:
# Check all columms to determine if duplicate values in column rows occur. 
# If duplicates occur, inspect column to determine why duplicates are occuring.

unique = len(dropped['Name of Covered Entity'].unique())
unique

# .unique() gives number or rows in column that are unique
# Note that for the column "Name of Covereed Entity", 
# 2101 unique rows are returned from 2083 rows in total

2094

In [14]:
# Unique values analysis - understand whether there is still missing data in some columns 
# or whether some values can be moved into one. 

print(dropped['Name of Covered Entity'].unique())

['Humana Inc' 'Delta Dental of Illinois' 'Providence Health Plan ' ...
 'Alaska Department of Health and Social Services'
 'Mid America Kidney Stone Association, LLC' 'Brooke Army Medical Center']

In [15]:
# look at where duplicates occur

#1. groupby

df_2 = dropped.groupby(['Name of Covered Entity']).count()
df_2

,State,Covered Entity Type,Individuals Affected,Breach Submission Date,Type of Breach,Location of Breached Information,Business Associate Present
Name of Covered Entity,,,,,,,
"AccuDoc Solutions, Inc.",1,1,1,1,1,1,1
Woodhull Medical and Mental Health Center,1,1,1,1,1,1,1
"101 Family Medical Group, Privacy Manager Breach",1,1,1,1,1,1,1
2020 On-Site Optometry,1,1,1,1,1,1,1
21st Century Oncology,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...
alma aguado md pa,1,1,1,1,1,1,1
inSite Digestive Health Care,1,1,1,1,1,1,1
mdINR LLC,1,1,1,1,1,1,1
vonica chau DDS PA,1,1,1,1,1,1,1
zarzamora family dental care,1,1,1,1,1,1,1

In [16]:
#2. filter df_2 by where > 1
df_2 = df_2[df_2['State'] > 1]
df_2

,State,Covered Entity Type,Individuals Affected,Breach Submission Date,Type of Breach,Location of Breached Information,Business Associate Present
Name of Covered Entity,,,,,,,
Administracion de Seguros de Salud - Triple S Salud Inc (BA),2,2,2,2,2,2,2
Aetna Inc.,2,2,2,2,2,2,2
"Aetna, Inc.",2,2,2,2,2,2,2
"Affinity Health Plan, Inc.",2,2,2,2,2,2,2
Aflac,2,2,2,2,2,2,2
...,...,...,...,...,...,...,...
"WellCare Health Plans, Inc.",3,3,3,3,3,3,3
West Sound Treatment Center,2,2,2,2,2,2,2
Wyoming Department of Health,3,3,3,3,3,3,3
Yale University,2,2,2,2,2,2,2
ZDI,3,3,3,3,3,3,3

In [17]:
#3. Can have a further look at where duplicates are occuring 
# filter duplicates to see why duplicates occur -- results tell us that this company has multiple breach dates

df_3 = dropped[dropped['Name of Covered Entity'] == 'Clearpoint Design, Inc.']
df_3

,Name of Covered Entity,State,Covered Entity Type,Individuals Affected,Breach Submission Date,Type of Breach,Location of Breached Information,Business Associate Present
1671,"Clearpoint Design, Inc.",MA,Business Associate,4100.0,2013-01-10,Hacking/IT Incident,Network Server,Yes
1673,"Clearpoint Design, Inc.",MA,Business Associate,7250.0,2013-01-10,Hacking/IT Incident,Network Server,Yes
1677,"Clearpoint Design, Inc.",MA,Business Associate,4125.0,2013-01-07,Hacking/IT Incident,Network Server,Yes
1682,"Clearpoint Design, Inc.",MA,Business Associate,4343.0,2012-12-28,Hacking/IT Incident,Network Server,Yes

# State

In [18]:
# 1. Check if duplicates occur for the remaining columns where applicable.
# 2. Investigate where duplicates occur 
# 3. Filter duplicates 

# 1.
unique_states = len(dropped['State' ].unique())
unique_states

52

In [19]:
# There should only be 50 states in the United States, inspect further to see why the above step returns 53 results
print(dropped['State'].unique())

['KY' 'IL' 'OR' 'PA' 'NC' 'CA' 'GA' 'MN' 'AZ' 'MD' 'IA' 'TX' 'MO' 'WA'
 'DC' 'CT' 'FL' 'NM' 'NJ' 'RI' 'MA' 'TN' 'VA' 'CO' 'AK' 'ID' 'MT' 'WI'
 'UT' 'OH' 'DE' 'NY' 'NV' 'AR' 'KS' 'MS' 'WV' 'AL' 'ME' 'WY' 'MI' 'OK'
 'LA' 'IN' 'SD' 'VT' 'NE' 'ND' 'NH' 'SC' 'HI' 'PR']

In [20]:
# sort states
print("\n".join(dropped['State'].sort_values().unique().tolist()))

# DC and PR - drop?

AK
AL
AR
AZ
CA
CO
CT
DC
DE
FL
GA
HI
IA
ID
IL
IN
KS
KY
LA
MA
MD
ME
MI
MN
MO
MS
MT
NC
ND
NE
NH
NJ
NM
NV
NY
OH
OK
OR
PA
PR
RI
SC
SD
TN
TX
UT
VA
VT
WA
WI
WV
WY

# Covered Entity Type

In [21]:
# Covered Entity Type
#1.
unique = len(dropped['Covered Entity Type'].unique())
unique

4

In [22]:
# Unique analysis --
print(dropped['Covered Entity Type'].unique())

['Health Plan' 'Business Associate' 'Healthcare Provider'
 'Healthcare Clearing House']

In [23]:
# Count 'Covered Entity Type' column as I will be using this in analysis as the industry variable 
entity__type_df = dropped.groupby(['Covered Entity Type']).count()
entity__type_df

# Healthcare provider is most represented

,Name of Covered Entity,State,Individuals Affected,Breach Submission Date,Type of Breach,Location of Breached Information,Business Associate Present
Covered Entity Type,,,,,,,
Business Associate,341,341,341,341,341,341,341
Health Plan,307,307,307,307,307,307,307
Healthcare Clearing House,4,4,4,4,4,4,4
Healthcare Provider,1656,1656,1656,1656,1656,1656,1656

# Type of Breach (Separate value/attribute)

In [24]:
# Type of breach 
#1. 
unique = len(dropped['Type of Breach' ].unique())
unique

30

In [26]:
print("\n".join(dropped['Type of Breach'].sort_values().unique().tolist()))

Hacking/IT Incident
Hacking/IT Incident, Improper Disposal, Loss, Other, Theft, Unauthorized Access/Disclosure, Unknown
Hacking/IT Incident, Other
Hacking/IT Incident, Other, Unauthorized Access/Disclosure
Hacking/IT Incident, Theft
Hacking/IT Incident, Theft, Unauthorized Access/Disclosure
Hacking/IT Incident, Unauthorized Access/Disclosure
Improper Disposal
Improper Disposal, Loss
Improper Disposal, Loss, Theft
Improper Disposal, Theft
Improper Disposal, Theft, Unauthorized Access/Disclosure
Improper Disposal, Unauthorized Access/Disclosure
Loss
Loss, Other
Loss, Other, Theft
Loss, Theft
Loss, Theft, Unauthorized Access/Disclosure, Unknown
Loss, Unauthorized Access/Disclosure
Loss, Unauthorized Access/Disclosure, Unknown
Loss, Unknown
Other
Other, Theft
Other, Theft, Unauthorized Access/Disclosure
Other, Unauthorized Access/Disclosure
Other, Unknown
Theft
Theft, Unauthorized Access/Disclosure
Unauthorized Access/Disclosure
Unknown

# Type of Breach Separation

In [33]:
# For the Type of Breach column, create a list of all unique values, 
# and add those as variables in the dataframe i.e. Hacking/IT incident, UnauthorisedAccess, 
# and fill in values 1 or 0 depending on whether the category exists for the companies. 

# Make a list of unique type of breach values
type_of_breaches = ['Hacking/IT Incident', 
                    'Other', 
                    'Unauthorized Access/Disclosure',
                    'Theft', 
                    'Improper Disposal', 
                    'Loss',
                    'Unknown',
                   ]

# Create new columns for these values in the dataframe
for value in type_of_breaches:
      dropped[value] = np.where(dropped['Type of Breach'].str.contains(value), 1, 0)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [34]:
# View new dataframe with Type of Breaches Columns separated 
dropped

,Name of Covered Entity,State,Covered Entity Type,Individuals Affected,Breach Submission Date,Type of Breach,Location of Breached Information,Business Associate Present,Hacking/IT Incident,Other,Unauthorized Access/Disclosure,Theft,Improper Disposal,Loss,Unknown
0,Humana Inc,KY,Health Plan,863.0,2019-06-03,Unauthorized Access/Disclosure,Network Server,No,0,0,1,0,0,0,0
1,Delta Dental of Illinois,IL,Business Associate,4216.0,2019-04-17,Hacking/IT Incident,Email,Yes,1,0,0,0,0,0,0
2,Providence Health Plan,OR,Health Plan,651.0,2019-03-19,Theft,Laptop,Yes,0,0,0,1,0,0,0
3,ZOLL Services LLC,PA,Healthcare Provider,277319.0,2019-03-18,Hacking/IT Incident,Network Server,Yes,1,0,0,0,0,0,0
4,Pasquotank-Camden Emergency Medical Service,NC,Healthcare Provider,20420.0,2019-02-28,Hacking/IT Incident,Network Server,No,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2310,"Mark D. Lurie, MD",CA,Healthcare Provider,5166.0,2009-11-20,Theft,Desktop Computer,No,0,0,0,1,0,0,0
2311,Health Services for Children with Special Need...,DC,Health Plan,3800.0,2009-11-17,Loss,Laptop,No,0,0,0,0,0,1,0
2312,Alaska Department of Health and Social Services,AK,Healthcare Provider,501.0,2009-10-30,Theft,"Other, Other Portable Electronic Device",No,0,0,0,1,0,0,0
2313,"Mid America Kidney Stone Association, LLC",MO,Healthcare Provider,1000.0,2009-10-28,Theft,Network Server,No,0,0,0,1,0,0,0
2314,Brooke Army Medical Center,TX,Healthcare Provider,1000.0,2009-10-21,Theft,Paper/Films,No,0,0,0,1,0,0,0

In [35]:
# eval number of hacking incidents
np.sum(dropped['Hacking/IT Incident'])

462

In [36]:
# apply np.sum() to all new type of breach columns that I created 
np.sum(dropped['Other'])

97

In [37]:
np.sum(dropped['Unauthorized Access/Disclosure'])

701

In [38]:
np.sum(dropped['Theft'])

883

In [39]:
np.sum(dropped['Improper Disposal'])

77

In [40]:
np.sum(dropped['Loss'])

177

In [41]:
np.sum(dropped['Unknown'])

16

# Location of Breached Information

In [44]:
# Location of Breached Information
#1. 
unique = len(dropped['Location of Breached Information' ].unique())
unique

72

In [45]:
# Unique analysis to find nan values
print(dropped['Location of Breached Information'].unique())

['Network Server' 'Email' 'Laptop' 'Paper/Films' 'Other'
 'Electronic Medical Record, Email'
 'Desktop Computer, Electronic Medical Record, Email, Network Server, Other, Other Portable Electronic Device, Paper/Films'
 'Other Portable Electronic Device, Paper/Films' 'Desktop Computer'
 'Desktop Computer, Network Server'
 'Desktop Computer, Email, Laptop, Network Server, Other Portable Electronic Device, Paper/Films'
 'Electronic Medical Record, Other' 'Other Portable Electronic Device'
 'Email, Laptop, Other Portable Electronic Device'
 'Electronic Medical Record'
 'Desktop Computer, Electronic Medical Record, Network Server'
 'Laptop, Other Portable Electronic Device'
 'Desktop Computer, Other, Other Portable Electronic Device, Paper/Films'
 'Desktop Computer, Email' 'Email, Other' 'Desktop Computer, Laptop'
 'Desktop Computer, Electronic Medical Record, Laptop'
 'Laptop, Paper/Films'
 'Desktop Computer, Electronic Medical Record, Email, Laptop, Network Server, Other, Other Portable Electronic Device, Paper/Films'
 'Electronic Medical Record, Network Server' 'Network Server, Other'
 'Desktop Computer, Email, Laptop, Network Server'
 'Desktop Computer, Laptop, Network Server'
 'Desktop Computer, Paper/Films'
 'Desktop Computer, Electronic Medical Record, Email, Network Server'
 'Electronic Medical Record, Paper/Films'
 'Desktop Computer, Electronic Medical Record, Email, Laptop, Other Portable Electronic Device'
 'Email, Paper/Films'
 'Desktop Computer, Electronic Medical Record, Email, Laptop, Other, Other Portable Electronic Device, Paper/Films'
 'Other, Paper/Films' 'Electronic Medical Record, Laptop'
 'Desktop Computer, Electronic Medical Record'
 'Network Server, Paper/Films'
 'Electronic Medical Record, Email, Laptop, Paper/Films'
 'Desktop Computer, Email, Network Server' 'Email, Laptop'
 'Email, Other Portable Electronic Device' 'Email, Laptop, Network Server'
 'Network Server, Other, Paper/Films' 'Email, Network Server'
 'Desktop Computer, Electronic Medical Record, Other'
 'Laptop, Network Server'
 'Desktop Computer, Other Portable Electronic Device'
 'Desktop Computer, Electronic Medical Record, Email, Laptop, Network Server'
 'Desktop Computer, Other'
 'Desktop Computer, Email, Laptop, Network Server, Other Portable Electronic Device'
 'Laptop, Other'
 'Desktop Computer, Laptop, Network Server, Other Portable Electronic Device'
 'Email, Laptop, Paper/Films'
 'Electronic Medical Record, Laptop, Network Server, Other, Other Portable Electronic Device'
 'Desktop Computer, Other Portable Electronic Device, Paper/Films'
 'Desktop Computer, Laptop, Paper/Films'
 'Email, Network Server, Other Portable Electronic Device'
 'Desktop Computer, Electronic Medical Record, Email, Laptop, Network Server, Other Portable Electronic Device'
 'Other, Other Portable Electronic Device'
 'Laptop, Other Portable Electronic Device, Paper/Films'
 'Desktop Computer, Email, Laptop, Network Server, Other, Other Portable Electronic Device'
 'Desktop Computer, Network Server, Paper/Films'
 'Desktop Computer, Laptop, Other Portable Electronic Device'
 'Desktop Computer, Electronic Medical Record, Email, Network Server, Paper/Films'
 'Desktop Computer, Electronic Medical Record, Email, Laptop, Network Server, Other Portable Electronic Device, Paper/Films'
 'Desktop Computer, Electronic Medical Record, Laptop, Network Server'
 'Desktop Computer, Electronic Medical Record, Email, Laptop, Network Server, Other, Other Portable Electronic Device'
 'Desktop Computer, Network Server, Other, Other Portable Electronic Device'
 'Desktop Computer, Other, Other Portable Electronic Device'
 'Desktop Computer, Laptop, Other, Other Portable Electronic Device'
 'Electronic Medical Record, Other, Other Portable Electronic Device']

In [46]:
#2.

location_breached_information_df = df.groupby(['Location of Breached Information']).count()
location_breached_information_df

,Name of Covered Entity,State,Covered Entity Type,Individuals Affected,Breach Submission Date,Type of Breach,Business Associate Present
Location of Breached Information,,,,,,,
Desktop Computer,154,154,154,153,154,154,154
"Desktop Computer, Electronic Medical Record",6,6,6,6,6,6,6
"Desktop Computer, Electronic Medical Record, Email, Laptop, Network Server",1,1,1,1,1,1,1
"Desktop Computer, Electronic Medical Record, Email, Laptop, Network Server, Other Portable Electronic Device",1,1,1,1,1,1,1
"Desktop Computer, Electronic Medical Record, Email, Laptop, Network Server, Other Portable Electronic Device, Paper/Films",1,1,1,1,1,1,1
...,...,...,...,...,...,...,...
Other Portable Electronic Device,133,132,133,133,133,133,133
"Other Portable Electronic Device, Paper/Films",3,3,3,3,3,3,3
"Other, Other Portable Electronic Device",47,47,47,47,47,47,47
"Other, Paper/Films",9,9,9,9,9,9,9
Paper/Films,514,513,514,514,514,514,514

In [47]:
# split into binary columns

# Business Associate Present

In [48]:
# Business Associate Present 
# 1. Ensure that there are only two response categories for this column: yes/no  
unique = len(dropped['Business Associate Present' ].unique())
unique

#2. Using .count() determine if there are more breaches with or without Business Associate present
associate_present_df = dropped.groupby(['Business Associate Present']).count()
associate_present_df

,Name of Covered Entity,State,Covered Entity Type,Individuals Affected,Breach Submission Date,Type of Breach,Location of Breached Information,Hacking/IT Incident,Other,Unauthorized Access/Disclosure,Theft,Improper Disposal,Loss,Unknown
Business Associate Present,,,,,,,,,,,,,,
No,1828,1828,1828,1828,1828,1828,1828,1828,1828,1828,1828,1828,1828,1828
Yes,480,480,480,480,480,480,480,480,480,480,480,480,480,480

# Clean column 'Name of Entity Covered' fields

In [ ]:
# Create a list of all unique names and sort them alphabetically so I can see what's different
print("\n".join(df['Name of Covered Entity'].sort_values().unique().tolist()))

In [ ]:
# In above results some names appear more than once.
# Remove whitespaces, Inc, commas, dots etc. using regular expressions
# Import regular expressions package
import re

In [ ]:
# Regular expressions
# search: rules for regular expressions to remove (ex.):"?" python 
# r raw
# Regular expression pattern to remove symbols
# stacking:  .str.replace
dropped['Name of Covered Entity clean'] = dropped.loc[:,'Name of Covered Entity'].replace(r'[/|\.|\"|\,|\&|\()|\[]|\-|\'|\]', "", regex=True).str.replace(r'\binc\b|\bllp\b|\bcorp\b|\bllc\b|\bpllc\b|\bpc\b|\bdba\b|\band\b', "", case=False, regex=True)
dropped['Name of Covered Entity clean']

In [ ]:
# View and inspect cleaned 'Name of Entity clean' column
print("\n".join(dropped['Name of Covered Entity clean'].sort_values().unique().tolist()))

In [ ]:
# View unique list of 'Name of Entity clean' column and see how the number of duplicates compares 
# to unclean fields column
unique = len(dropped['Name of Covered Entity clean'].unique())
unique

# result gives 1883 vs, original before cleaning = 1899

In [ ]:
dropped

In [ ]:
# Export dropped dataframe as csv to use in UNIT 7 EDA notebook
# Don't forget to add '.csv' at the end of the path
export_csv = dropped.to_csv (r'C:\Users\Mandi\Desktop\export_dataframe.csv', index = None, header=True)

In [ ]:
export_csv